services:
  db:
    image: jvboronatjosep/mi_cine2:v2
    container_name: contenedorMiCine2
    ports:
      - "3306:3306"
  php:
    image: jvboronatjosep/mi_app_cine2:v2
    container_name: contenedorMiApp2
    ports:
      - "8080:80"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contenedorPhpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: contrasenyaRoot
    ports:
      - "8081:80"
    depends_on:
      - db